### ISSUE TITLE
Multi Account Hierarchy - Invite - Email required

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#12]
Module 1: Security Hub Walkthrough -> Multi Account Hierarchy

It appears that the `Email address` field is now a required field before one can add an account (even when pressing <TAB> as suggested

![Screen Shot 2020-10-23 at 3 36 13 PM](https://user-images.githubusercontent.com/3401492/96969975-8ef0bb00-1545-11eb-9dc9-564f18b1aa66.png)

The steps/guidance requires an update to align

**Comment by jcriswell** [comment]
udpated in commit a0e8502fff94bd0d80ce6c84add1ad153bbce28f
