### ISSUE TITLE
Module 1: Security Hub Walkthrough - Update to new UI

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#13]
Module 1: Security Hub Walkthrough

>Click View Results for CIS AWS Foundations Benchmark v1.2.0.

Screenshots and steps to be adjusted to reflected the updated Security Hub standards UI for Security Standards

The updated UI is as follows:
![Screen Shot 2020-10-23 at 3 43 43 PM](https://user-images.githubusercontent.com/3401492/96970646-96649400-1546-11eb-9f5d-53d42e0b1e8d.png)

**Comment by jcriswell** [comment]
fixed in commit a0e8502fff94bd0d80ce6c84add1ad153bbce28f
