### ISSUE TITLE
Filter operator 'EQUALS' does not exist

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#14]
Module 2: Custom Insights and Custom Findings

The filter operator of 'EQUALS' is not available in current UI - the equivalent is now 'IS'

![Screen Shot 2020-10-23 at 3 40 02 PM](https://user-images.githubusercontent.com/3401492/96970330-19d1b580-1546-11eb-9205-77880987551c.png)

![Screen Shot 2020-10-23 at 3 56 28 PM](https://user-images.githubusercontent.com/3401492/96971943-6d450300-1548-11eb-99f7-11fbde124a7b.png)

**Comment by jcriswell** [comment]
fixed for module 2 in commit a0e8502fff94bd0d80ce6c84add1ad153bbce28f
