### ISSUE TITLE
Module 3 - Event Pattern - Suggested clarification

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#15]
Module 3: Remediation and Response CIS Benchmark and Custom Action

>Copy and paste in the custom event pattern below. Use the ARN you recorded for your Security Hub Custom Action

```
{ 
"source": [ 
    "aws.securityhub" 
  ], 
  "detail-type": [ 
    "Security Hub Findings - Custom Action" 
  ], 
  "resources": [ 
     "arn:aws:securityhub:us-east-1:[YOUR-ACCOUNT-ID]:action/custom/IsolateInstance" 
  ] 
} 
```

In the above sample a user may potentially substitute their AWS account ID (rather than replace with the full arn) - which would result in a failure if they were not doing the lab in `us-east-1`

There is something similar in Module 4.

**Comment by jcriswell** [comment]
fixed in commit a0e8502fff94bd0d80ce6c84add1ad153bbce28f
