### ISSUE TITLE
Module 3 - Security Group - UI location

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#16]
Module 3: Remediation and Response CIS Benchmark and Custom Action

>Isolate the security group on an EC2 Instance
>1. In the Description tab for the instance record the name of the current security group.

The EC2 UI has been updated, and the Security Group is no longer shown at this location. The user would need to click the 'Security' tab, then take note of the Security Group name

![Screen Shot 2020-10-23 at 4 08 04 PM](https://user-images.githubusercontent.com/3401492/96973102-07597b00-154a-11eb-97a7-9887b8708c56.png)

**Comment by jcriswell** [comment]
updated in commit a0e8502fff94bd0d80ce6c84add1ad153bbce28f
