### ISSUE TITLE
CloudFormation template - Open in New Tab

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#17]
Module 3: Remediation and Response CIS Benchmark and Custom Action

>Deploy remediation playbooks for CIS Benchmarks
>Deploy remediation playbooks via CloudFormation
>Download CloudFormation template from GitHub.

Suggest that the `CloudFormation template` hyperlink is updated to open in new tab/window

**Comment by jcriswell** [comment]
added in commit a0e8502fff94bd0d80ce6c84add1ad153bbce28f
