### ISSUE TITLE
Module 3 - Step Numbering

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#18]
Module 3: Remediation and Response CIS Benchmark and Custom Action

>Please wait a moment for the creation to complete or progress to start, then proceed to Step 11.

However, the steps restart from 1 

![Screen Shot 2020-10-23 at 4 39 53 PM](https://user-images.githubusercontent.com/3401492/96976442-6faa5b80-154e-11eb-9cbd-75180dae8899.png)

**Comment by scottbward** [comment]
Push that was done today has corrected the number sequencing in all the docs for this workshop.
