### ISSUE TITLE
Module 4 - Store Slack webhook secret securely [Enhancement]

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-security-hub-workshop#20]
Currently the Slack webhook is being stored as an environment variable within the Lambda function. Consider changing to store in either SSM Parameter Store as a SecureString or within AWS Secrets Manager, and have the Lambda function fetch this secret at run time.

**Comment by jcriswell** [comment]
The current plan to is replace this section with AWS ChatBot.  That would solve this and provide the other features of Slack integration via ChatBot.

**Comment by jaegernh** [comment]
We are moving the workshop to a new system. This feedback has been noted. Thank you.
