### ISSUE TITLE
Module 1:  repeated word "and"

### ISSUE THREAD

**Issue by brayansteven-reyes** [aws-samples/aws-security-hub-workshop#21]
Double and in the integration section:

Integrations
In this section, we will walk through the Security Hub side of enabling a partner integration. Security Hub provides the ability to integrate security findings from AWS services and third-party products. For third-party products Security Hub gives you the ability to selectively enable the integrations _**and and**_ provides a link to the configuration instructions related to the third-party product.

**Comment by scottbward** [comment]
Update to correct this in the documentation has been pushed.
