### ISSUE TITLE
[Enhancement] Module 0: Move setup files into a public bucket to eliminate bucket creation step

### ISSUE THREAD

**Issue by senorkrabs** [aws-samples/aws-security-hub-workshop#22]
For a simpler participant experience, it would be great if AWS published the deployment files to a public S3 bucket that could be used to deploy the CloudFormation stacks. Many other workshops and AWS solutions take this approach and it saves setup time and eliminates potential issues during deployment (i.e. accidentally copying the files into a `/deploy` prefix in the bucket, which  then causes an Access Denied error when attempting to launch with the URL supplied in the instructions.

**Comment by scottbward** [comment]
Good suggestion.  This is something that we are actively working on so stay tuned for an update that addresses this in the near future.

**Comment by scottbward** [comment]
An update has been pushed so that the templates and the functions for this workshop are now sources from a central S3 bucket.  There is no longer the need to download and stage the additional assets.
