### ISSUE TITLE
Module 0: Environment Build: Confusion over enabling security services

### ISSUE THREAD

**Issue by ckamps** [aws-samples/aws-security-hub-workshop#24]
When colleagues and I ran the workshop with ~20 people in the past several weeks, ~5 of the participants inadvertently manually enabled some of the security services when checking the status of the services.  When they attempted to create the CloudFormation stack with the parameters set to "Y" to enable the services, they encountered stack creation failures.

### Suggested fix

Clarify that when using a new AWS account, you do not need to check the current status of the security services. Instead, you can proceed directly to the CloudFormation stack creation section.

Additionally, emphasize that the user should specify "Yes-..." for the security service parameters in the stack when they're using a new account.

**Comment by jaegernh** [comment]
This has been re-worked. Thank you for the feedback. Resolved.
