### ISSUE TITLE
Module 0 environment build -- auto enable services

### ISSUE THREAD

**Issue by ghost** [aws-samples/aws-security-hub-workshop#6]
I have tested building this stack from a new account and auto enabling of services.
GuardDuty fails on Auto Enable even with new accounts never accessing the account.
SH and Config also fail on the same process.

I found that going to SH on a fresh new account still shows it as enabled by default.
Config and GuardDuty do not however the CFT enable feature is generating an error so still created the Config rules manually and set Config auto enable to No in order to build this stack successful.

**Comment by ghost** [comment]
GuardDutyTesterTemplate | CREATE_FAILED | Embedded stack arn:aws:cloudformation:us-east-1:xxxyyyyzzzzzzz:stack/aws-meetup-sh-workshop-stack-GuardDutyTesterTemplate-111WU0YPHKMWQ/21b4f530-d277-11ea-9da4-0e3038696552 was not successfully created: The following resource(s) failed to create: [RedTeam].

(I removed the ARN on this comment post for security purposes)

**Comment by ghost** [comment]
I got the exact same error as noneil277 above when:
- Config & Security HUB are not pre-enabled and I select ‘YES” to be enabled by the template 
- GuardDuty pre-enabled and I select “NO” to be enabled by the template

and when all three are pre-enabled by default. 
It didn't work for me when disabling all three either, and selecting ‘YES” for all of them to be enabled by the template.

In all cases, I tried with a brand new AWS account.

**Comment by scottbward** [comment]
@noneil277 @monicaalcalde Thank you for your feedback.  Sorry that you are running into some issues with deploying the workshop.
I would like to clarify the current issues that you are receiving.  The failure that is being reported from the GuardDutyTesterTemplate, where the RedTeam resource failed to create, is related to an EC2 resource which the template creates to help with generation of GuardDuty findings.   What I would like to know is if both of you are only seeing the the failure to create the RedTeam resource or if you are seeing other failures related to the steps for actually enabling the GuardDuty, Security Hub, and Config services.    
Would it be possible to post the errors you are receiving related to CloudFormation trying to enable the GuardDuty, Security Hub, and Config resources?

**Comment by scottbward** [comment]
closing this issue after no further feedback.    Most likely cause for this is running the template in a brand new account before the account could be baselined to allow launching of EC2 instances.
